// PDF report renderer — builds paginated drawing primitives for the pdfWriter
// serializer. Zero external dependencies; base-14 fonts only, so amounts are
// rendered as "Rs." (₹ is not encodable in WinAnsi — the UI and CSV keep ₹).

import { buildPDF } from './pdfWriter.js';

const W = 595.28;
const M = 40;
const TOP = 40;
const BOTTOM_LIMIT = 790;

const INK = '#1c2333';
const MUTED = '#6b7280';
const NAVY = '#0f172a';
const ZEBRA = '#f8f9fc';
const LINE = '#e5e7eb';

function formatINR(num) {
  return 'Rs.' + Number(num || 0).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

// Approximate Helvetica advance width — used only for truncation heuristics.
function fitText(text, maxWidth, size) {
  const s = String(text ?? '');
  const maxChars = Math.max(1, Math.floor(maxWidth / (size * 0.5)));
  return s.length > maxChars ? s.slice(0, Math.max(1, maxChars - 3)) + '...' : s;
}

/**
 * renderReportPDF — generic tabular report.
 *  columns: [{ label, key, width, num?, money? }]   (num = right-aligned, money = INR formatted)
 *  rows: array of plain objects (keys match column.key)
 *  summary: array of strings rendered as bold totals lines after the table
 *  filters: array of { label, value } rendered under the header
 */
export function renderReportPDF({ title, generatedBy, filters = [], columns = [], rows = [], summary = [] }) {
  const pages = [];
  let prims = [];
  let y = TOP;

  const totalWidth = columns.reduce((a, c) => a + c.width, 0);
  const scale = totalWidth > W - M * 2 ? (W - M * 2) / totalWidth : 1;
  const cols = columns.map((c) => ({ ...c, width: c.width * scale }));
  const tableWidth = cols.reduce((a, c) => a + c.width, 0);

  const pushPage = () => {
    // Footer on every page
    prims.push({ type: 'line', x1: M, y1: 808, x2: W - M, y2: 808, color: LINE });
    prims.push({ type: 'text', text: "Generated by Men's Collection Management System", x: M, y: 820, size: 8, color: MUTED });
    prims.push({ type: 'text', text: `Page ${pages.length + 1}`, x: W - M - 40, y: 820, size: 8, color: MUTED });
    pages.push(prims);
    prims = [];
    y = TOP;
  };

  const drawTableHeader = () => {
    prims.push({ type: 'rect', x: M, y, w: tableWidth, h: 20, fill: NAVY });
    let x = M + 4;
    for (const col of cols) {
      prims.push({ type: 'text', text: fitText(col.label, col.width - 8, 8), x: col.num ? x - 8 + col.width - 4 : x, y: y + 13, size: 8, bold: true, color: '#ffffff' });
      x += col.width;
    }
    y += 22;
  };

  // ---- Page 1 header block ----
  prims.push({ type: 'text', text: "Men's Collection Management System", x: M, y: y + 10, size: 16, bold: true, color: NAVY });
  y += 30;
  prims.push({ type: 'text', text: title, x: M, y, size: 12, color: MUTED });
  y += 14;
  const generated = `Generated: ${new Date().toLocaleString('en-IN')}${generatedBy ? `   |   By: ${generatedBy}` : ''}`;
  prims.push({ type: 'text', text: generated, x: M, y, size: 9, color: MUTED });
  y += 12;
  if (filters.length) {
    const filterText = filters.filter((f) => f.value !== undefined && f.value !== null && f.value !== '').map((f) => `${f.label}: ${f.value}`).join('   |   ');
    if (filterText) {
      prims.push({ type: 'text', text: fitText(`Filters — ${filterText}`, W - M * 2, 9), x: M, y, size: 9, color: MUTED });
      y += 12;
    }
  }
  prims.push({ type: 'text', text: 'All amounts in INR', x: M, y, size: 8, color: MUTED });
  y += 12;
  prims.push({ type: 'line', x1: M, y1: y, x2: W - M, y2: y, color: LINE });
  y += 12;

  drawTableHeader();

  rows.forEach((row, i) => {
    if (y > BOTTOM_LIMIT) {
      pushPage();
      prims.push({ type: 'text', text: `${title} (continued)`, x: M, y, size: 10, bold: true, color: NAVY });
      y += 16;
      drawTableHeader();
    }
    if (i % 2 === 0) prims.push({ type: 'rect', x: M, y, w: tableWidth, h: 17, fill: ZEBRA });
    let x = M + 4;
    for (const col of cols) {
      let val = row[col.key];
      if (val === null || val === undefined) val = '';
      if (col.money) val = formatINR(Number(val));
      else if (col.num) val = Number(val).toLocaleString('en-IN');
      const text = fitText(val, col.width - 8, 8);
      prims.push({ type: 'text', text, x: col.num || col.money ? x + col.width - 8 - text.length * 4 : x, y: y + 11, size: 8, color: INK });
      x += col.width;
    }
    y += 17;
  });

  if (y > BOTTOM_LIMIT - 40) pushPage();
  y += 8;
  prims.push({ type: 'line', x1: M, y1: y, x2: W - M, y2: y, color: LINE });
  y += 12;
  for (const line of summary) {
    prims.push({ type: 'text', text: line, x: M, y, size: 10, bold: true, color: INK });
    y += 13;
  }
  pushPage();

  return buildPDF(pages);
}

// CSV with proper escaping, UTF-8 BOM so Excel renders ₹ and commas correctly.
export function generateCSV(headers, rows) {
  const escape = (val) => {
    const s = String(val ?? '');
    if (s.includes(',') || s.includes('"') || s.includes('\n')) return `"${s.replace(/"/g, '""')}"`;
    return s;
  };
  const lines = [headers.map(escape).join(',')];
  for (const row of rows) {
    lines.push(row.map(escape).join(','));
  }
  return '\ufeff' + lines.join('\n');
}

// Legacy thin wrappers (kept for compatibility with earlier call sites).
export function generateProductReportPDF(products, filters = {}) {
  return renderReportPDF({
    title: 'Product Report',
    filters: [
      { label: 'Category', value: filters.category },
      { label: 'Brand', value: filters.brand },
      { label: 'Status', value: filters.status },
    ],
    columns: [
      { label: 'SKU', key: 'sku', width: 80 },
      { label: 'Product Name', key: 'name', width: 140 },
      { label: 'Category', key: 'category_name', width: 80 },
      { label: 'Brand', key: 'brand_name', width: 70 },
      { label: 'Purchase', key: 'purchase_price', width: 70, money: true },
      { label: 'Selling', key: 'selling_price', width: 70, money: true },
      { label: 'Margin %', key: 'profit_margin', width: 65, num: true },
    ],
    rows: products,
    summary: [
      `Total Products: ${products.length}`,
      `Total Selling Value: ${formatINR(products.reduce((s, p) => s + Number(p.selling_price || 0), 0))}`,
    ],
  });
}

export function generateOrderReportPDF(orders, filters = {}) {
  return renderReportPDF({
    title: 'Purchase Order Report',
    columns: [
      { label: 'PO Number', key: 'po_number', width: 110 },
      { label: 'Date', key: 'po_date', width: 80 },
      { label: 'Supplier', key: 'supplier_name', width: 130 },
      { label: 'Status', key: 'status', width: 80 },
      { label: 'Grand Total', key: 'grand_total', width: 105, money: true },
    ],
    rows: orders,
    summary: [
      `Total Orders: ${orders.length}`,
      `Grand Total: ${formatINR(orders.reduce((s, o) => s + Number(o.grand_total || 0), 0))}`,
    ],
  });
}
