import { useState, useEffect, useCallback } from 'react';
import api, { errMessage } from '../api.js';
import { useAuth } from '../auth.jsx';
import Icon from '../components/Icon.jsx';

const EXPORT_TYPES = [
  { key: 'orders', label: 'Orders' },
  { key: 'users', label: 'Users' },
  { key: 'production', label: 'Production' },
];

export default function CsvExports() {
  const { hasPermission } = useAuth();
  const canExport = hasPermission('csv.export');
  const [history, setHistory] = useState([]);
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);
  const [exportType, setExportType] = useState('orders');
  const [filters, setFilters] = useState({ from: '', to: '', status: '' });

  const loadHistory = useCallback(() => {
    api.get('/csv-exports').then((r) => setHistory(r.data.data)).catch((e) => setError(errMessage(e)));
  }, []);

  useEffect(() => { loadHistory(); }, [loadHistory]);

  async function doExport() {
    setBusy(true); setError('');
    try {
      const body = {};
      if (filters.from) body.from = filters.from;
      if (filters.to) body.to = filters.to;
      if (filters.status) body.status = filters.status;
      const { data } = await api.post(`/csv-exports/${exportType}`, body);
      // Download the CSV
      if (data.data.csv) {
        const blob = new Blob([data.data.csv], { type: 'text/csv' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url; a.download = data.data.file_name; a.click();
        URL.revokeObjectURL(url);
      }
      loadHistory();
    } catch (e) { setError(errMessage(e)); } finally { setBusy(false); }
  }

  if (!canExport) return <div className="page"><div className="alert error">You do not have permission to export data.</div></div>;

  return (
    <div className="page">
      <h1 className="page-title">CSV Exports</h1>
      <p className="page-sub">Export system data to CSV files for external analysis</p>
      {error && <div className="alert error">{error}</div>}

      <div className="panel">
        <h3>Generate Export</h3>
        <div className="row" style={{ alignItems: 'flex-end', gap: 12 }}>
          <label className="field" style={{ minWidth: 160 }}>
            <span className="field-label">Export Type</span>
            <select value={exportType} onChange={(e) => setExportType(e.target.value)}>
              {EXPORT_TYPES.map((t) => <option key={t.key} value={t.key}>{t.label}</option>)}
            </select>
          </label>
          <label className="field">
            <span className="field-label">From</span>
            <input type="date" value={filters.from} onChange={(e) => setFilters({ ...filters, from: e.target.value })} />
          </label>
          <label className="field">
            <span className="field-label">To</span>
            <input type="date" value={filters.to} onChange={(e) => setFilters({ ...filters, to: e.target.value })} />
          </label>
          {exportType === 'orders' && (
            <label className="field" style={{ minWidth: 140 }}>
              <span className="field-label">Status</span>
              <select value={filters.status} onChange={(e) => setFilters({ ...filters, status: e.target.value })}>
                <option value="">All</option>
                <option value="draft">Draft</option>
                <option value="submitted">Submitted</option>
                <option value="approved">Approved</option>
                <option value="in_production">In Production</option>
                <option value="completed">Completed</option>
                <option value="cancelled">Cancelled</option>
              </select>
            </label>
          )}
          <button className="btn primary" disabled={busy} onClick={doExport}>
            <Icon name="download" size={14} /> {busy ? 'Exporting…' : 'Export CSV'}
          </button>
        </div>
      </div>

      <div className="panel">
        <h3>Export History</h3>
        <table className="grid">
          <thead>
            <tr><th>File</th><th>Type</th><th>Rows</th><th>Generated By</th><th>Date</th><th>Size</th><th></th></tr>
          </thead>
          <tbody>
            {history.map((h) => (
              <tr key={h.id}>
                <td className="mono">{h.file_name}</td>
                <td><span className="chip">{h.export_type}</span></td>
                <td>{h.file_size ? `${(h.file_size / 1024).toFixed(1)} KB` : '—'}</td>
                <td>{h.generated_by_name || '—'}</td>
                <td className="muted">{new Date(h.created_at).toLocaleString('en-IN')}</td>
                <td>{h.file_size ? `${(h.file_size / 1024).toFixed(1)} KB` : '—'}</td>
                <td>
                  <a className="btn sm" href={h.url} download>
                    <Icon name="download" size={13} /> Download
                  </a>
                </td>
              </tr>
            ))}
            {!history.length && <tr><td colSpan={7} className="muted">No exports yet.</td></tr>}
          </tbody>
        </table>
      </div>
    </div>
  );
}
